[package]
name = "tcp-server"
version = "0.1.0"
edition = "2024"

[dependencies]
async-std = "1.13.1"
rand = "0.9.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tokio = { version = "1.45.1", features = ["full"] }
